name: digitaler_buecherschrank
description: Too wild.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+0

environment:
  sdk: ">=2.12.0-0 <3.0.0"

 
dependencies:
  # For imported flutter_login sources
  font_awesome_flutter: ^9.0.0
  another_transformer_page_view: ^1.0.0
  another_flushbar: ^1.10.17
  quiver: ^3.0.0
  #
  intl_utils: ^2.3.0
  json_annotation: ^4.0.1

  # enabling 90 hz
  flutter_displaymode: ^0.3.1-nullsafety.0

  # UI Stuff
  flutter_launcher_icons: ^0.9.0
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.3
  flutter_staggered_animations: ^1.0.0
  dependency_validator: ^3.1.0
  material_floating_search_bar: ^0.3.4
  sliding_up_panel: ^2.0.0+1
  flutter_native_splash: ^1.1.8+4
  blur: ^3.0.0
  flex_color_scheme: ^3.0.1
  implicitly_animated_reorderable_list: ^0.4.0
  grouped_list: ^4.0.0
  pull_to_refresh: ^2.0.0
  maps_toolkit:
    git:
      url: git://github.com/edgarfroes/maps_toolkit.git

  # Diverse Utilities
  google_fonts: ^2.0.0
  location: ^4.1.1
  http: ^0.13.3
  rxdart: ^0.27.0
  connectivity_plus: ^1.0.1
  flutter_barcode_scanner: ^2.0.0
  provider: ^6.0.0
  jwt_decode: ^0.3.1
  path_provider: ^2.0.1
  uuid: ^3.0.4
  restart_app: ^1.0.3
  dio: ^4.0.0
  responsive_framework: ^0.1.4
  dio_smart_retry: ^1.0.2
  flutter_bcrypt: ^1.0.7
  introduction_screen: ^2.1.0
  streaming_shared_preferences: ^2.0.0
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  build_runner: ^2.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - assets/icons/
     - assets/google_fonts/
     - assets/map_styles/
     - assets/intro/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: false
  ios: true
  image_path: "assets/icons/icon.png"

flutter_intl:
  main_locale: de
  enabled: true
  localizely:
    project_id: 5989b48b-d779-46f3-b254-74fabfc2aa9e